
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 13 13:19:31 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 28;
  public static final int LTE = 35;
  public static final int LBRACKET = 42;
  public static final int CONST = 9;
  public static final int NAMESPACE = 17;
  public static final int NUMCONST = 45;
  public static final int LPAREN = 23;
  public static final int SEMI = 21;
  public static final int CONTINUE = 14;
  public static final int FOR = 15;
  public static final int MINUS = 19;
  public static final int STATIC = 16;
  public static final int RPAREN = 24;
  public static final int AND = 36;
  public static final int LT = 34;
  public static final int OR = 37;
  public static final int COMMA = 22;
  public static final int CLASS = 7;
  public static final int INC = 38;
  public static final int PLUS = 18;
  public static final int IF = 10;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 20;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PERCENT = 29;
  public static final int NEQ = 31;
  public static final int IDENT = 46;
  public static final int BREAK = 6;
  public static final int VOID = 5;
  public static final int EQ = 30;
  public static final int GTE = 33;
  public static final int TIMES = 27;
  public static final int ARROW = 44;
  public static final int COLON = 40;
  public static final int LBRACE = 25;
  public static final int ELSE = 8;
  public static final int READ = 12;
  public static final int CHARCONST = 47;
  public static final int RBRACE = 26;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int DEC = 39;
  public static final int GT = 32;
  public static final int PRINT = 3;
}

